Khalil/setup script (#70)
* Updated setup script to install dependencies for Linux and MacOSX
Changed uart0_min to a file name that fits the style guide
Removed warning temp file accedently commit in previous merge
Removed Lx_<> library includes in makefile. Now you will need a verbose
include path to include a project

* Adding travis file to test CI on MacOSX

* updating travis ci to see it appear on travis ci

* changed bin -> binaries in travis ci file

* Removing dependency check in setup

* add the argument word "accept" into xcodebuild

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -34,6 +34,16 @@ then
 fi
 
 echo " ──────────────────────────────────────────────────┐"
+echo "  List of global software installed:                "
+echo "   1) Python                                        "
+echo "   2) Python pip                                    "
+echo "   3) Curl                                          "
+echo "   4) Git CLI                                       "
+echo "   5) Perl                                          "
+echo "   6) OpenOCD (Debian/Ubuntu Only)                  "
+echo "   7) XCode CLI tools (MacOS Only)                  "
+echo "   7) Build Essential tools (Debian/Ubuntu Only)    "
+echo "└────────────────────────────────────────────────── "
 echo "            Acquiring sudo privileges               "
 echo "└────────────────────────────────────────────────── "
 sudo echo "" || exit 1
@@ -44,9 +54,16 @@ ARCH=$(uname -m)
 # Get System Operating System
 OS=$(uname -s)
 # Get base path
-BASE=`pwd`
+BASE=$(pwd)
 # Define name of the arm version we are downloading
-ARM_GCC=gcc-arm-none-eabi-6-2017-q2-update
+ARM_GCC_URL="https://developer.arm.com/-/media/Files/downloads/gnu-rm/7-2017q4/"
+ARM_GCC_COMMON="gcc-arm-none-eabi-7-2017-q4-major"
+ARM_GCC_ARCHIVE_FILE_LINUX="$ARM_GCC_COMMON-linux.tar.bz"
+ARM_GCC_ARCHIVE_FILE_MAC="$ARM_GCC_COMMON-mac.tar.bz"
+ARM_GCC_ARCHIVE_LINUX_URL="$ARM_GCC_URL$ARM_GCC_ARCHIVE_FILE_LINUX"
+ARM_GCC_ARCHIVE_MAC_URL="$ARM_GCC_URL$ARM_GCC_ARCHIVE_FILE_MAC"
+
+# https://developer.arm.com/-/media/Files/downloads/gnu-rm/7-2017q4/gcc-arm-none-eabi-7-2017-q4-major-linux.tar.bz
 
 echo " ──────────────────────────────────────────────────┐"
 echo ""
@@ -69,26 +86,28 @@ PYTHON_INSTALLED=$(check $(programInstalled python))
 PIP_INSTALLED=$(check $(programInstalled pip))
 GIT_INSTALLED=$(check $(programInstalled git))
 PERL_INSTALLED=$(check $(programInstalled perl))
+MAKE_INSTALLED=$(check $(programInstalled make))
 # Output results of dependencies
-echo "python        $PYTHON_INSTALLED"
-echo "pip           $PIP_INSTALLED"
-echo "git           $GIT_INSTALLED"
-echo "perl          $PERL_INSTALLED"
+# echo "python        $PYTHON_INSTALLED"
+# echo "perl          $PERL_INSTALLED"
+# echo "git           $GIT_INSTALLED"
+# echo "make          $MAKE_INSTALLED"
+# echo "pip           $PIP_INSTALLED"
 # Concat results
-REQUIREMENTS_MET="$PYTHON_INSTALLED $PIP_INSTALLED $GIT_INSTALLED $PERL_INSTALLED"
+# REQUIREMENTS_MET="$PYTHON_INSTALLED $PIP_INSTALLED $GIT_INSTALLED $PERL_INSTALLED"
 # This lines uses wildcards to check if there exists a ✘ in the
 # Concatenated string above. If it does, terminate setup
-if [[ $REQUIREMENTS_MET == *"✘"* ]]
-then
-	echo "Missing requirement(s). Please install manually. Setup exiting."
-	exit 1
-fi
+# if [[ $REQUIREMENTS_MET == *"✘"* ]]
+# then
+# 	echo "Missing requirement(s). Please install manually. Setup exiting."
+# 	exit 1
+# fi
 echo " ──────────────────────────────────────────────────┐"
 echo "               System Dependent Setup               "
 echo "└────────────────────────────────────────────────── "
 cd $TOOLDIR
 case "$OS" in
-	Linux) # Linux Case
+	Linux) # Linux & Windows WSL Case
 		echo "Operating System: Linux"
 		SJSUONEDEV=/dev/ttyUSB0
 		echo " ───────────────────────────────────────────────────┐"
@@ -96,9 +115,13 @@ case "$OS" in
 		echo "└─────────────────────────────────────────────────── "
 		sudo apt -y install openocd
 		echo " ───────────────────────────────────────────────────┐"
-		echo "         Updating Git, Python, PIP, and Curl         "
+		echo "        Installing build-essentials (GCC, make)      "
 		echo "└─────────────────────────────────────────────────── "
-		sudo apt -y install git python python-pip curl
+		sudo apt -y install build-essential
+		echo " ───────────────────────────────────────────────────┐"
+		echo "      Installing Git, Python, PIP, Curl and Perl     "
+		echo "└─────────────────────────────────────────────────── "
+		sudo apt -y install git python python-pip curl perl
 		echo " ──────────────────────────────────────────────────┐"
 		echo "      Adding current user to '$GROUP' group"
 		echo "└────────────────────────────────────────────────── "
@@ -107,25 +130,31 @@ case "$OS" in
 		echo " ──────────────────────────────────────────────────┐"
 		echo "           Downloading gcc-arm-embedded             "
 		echo "└────────────────────────────────────────────────── "
-		curl -C - -LO https://developer.arm.com/-/media/Files/downloads/gnu-rm/6-2017q2/$ARM_GCC-linux.tar.bz2
-		GCC_PKG=$ARM_GCC-linux.tar.bz2
+		curl -C - -LO $ARM_GCC_ARCHIVE_LINUX_URL
+		GCC_PKG=$ARM_GCC_ARCHIVE_FILE_LINUX
 		;;
 
 	Darwin) # OS X Case
 		echo "Operating System: Mac OSX Darvin"
 		SJSUONEDEV=/dev/tty.usbserial-A503JOLS
-		# ========= Xcode ========== #
-		# xcode-select --install &> /dev/null	# Install Command Line tools (make etc...)
-		# sudo xcodebuild -license # Accept User Agreement
-		echo " ───────────────────────────────────────────────────┐"
-		echo "           Using EASY_INSTALL to install PIP         "
+        echo " ───────────────────────────────────────────────────┐"
+		echo "    Install XCode Command Line Tools (GCC, make)     "
+		echo "└─────────────────────────────────────────────────── "
+        xcode-select --install &> /dev/null	# Install Command Line tools (make etc...)
+		sudo xcodebuild -license accept # Accept User Agreement
+        echo " ───────────────────────────────────────────────────┐"
+		echo "          Prompt Git installer by invoking it        "
+		echo "└─────────────────────────────────────────────────── "
+        git --version
+        echo " ───────────────────────────────────────────────────┐"
+		echo "          Using EASY_INSTALL to install PIP          "
 		echo "└─────────────────────────────────────────────────── "
 		sudo easy_install pip
 		echo " ──────────────────────────────────────────────────┐"
-		echo "           Downloading gcc-arm-embedded             "
+		echo "            Downloading gcc-arm-embedded            "
 		echo "└────────────────────────────────────────────────── "
-		curl -C - -LO https://developer.arm.com/-/media/Files/downloads/gnu-rm/6-2017q2/$ARM_GCC-mac.tar.bz2
-		GCC_PKG=$ARM_GCC-mac.tar.bz2
+		curl -C - -LO $ARM_GCC_ARCHIVE_MAC_URL
+		GCC_PKG=$ARM_GCC_ARCHIVE_FILE_MAC
 		;;
 
 	*)	#Default if Operating System other than Mac or Linux
@@ -140,9 +169,9 @@ echo "└───────────────────────�
 tar --extract \
 	--verbose \
 	--bzip2 \
-	--file=$GCC_PKG\
+	--file="$GCC_PKG"\
 	--exclude='share/doc' 2> /dev/null
-cd $BASE
+cd "$BASE"
 echo " ───────────────────────────────────────────────────┐"
 echo "                   Upgrading PIP                     "
 echo "└─────────────────────────────────────────────────── "
@@ -152,31 +181,29 @@ echo "            Upgrading Python's Virtualenv            "
 echo "└─────────────────────────────────────────────────── "
 sudo -H pip install --upgrade virtualenv
 echo " ───────────────────────────────────────────────────┐"
-echo "                 Installing GDBGUI                   "
-echo "└─────────────────────────────────────────────────── "
-sudo -H pip install --upgrade gdbgui
-echo " ───────────────────────────────────────────────────┐"
 echo "                Setting Up Hyperload                 "
 echo "└─────────────────────────────────────────────────── "
-git clone --depth=1 https://github.com/kammce/Hyperload.git $TOOLDIR/Hyperload/
-cd $TOOLDIR/Hyperload/ && ./setup
-cd $BASE
+rm -rf "$TOOLDIR/Hyperload/"
+git clone --depth=1 https://github.com/kammce/Hyperload.git "$TOOLDIR/Hyperload/"
+cd "$TOOLDIR/Hyperload/" && ./setup
+cd "$BASE"
 echo " ───────────────────────────────────────────────────┐"
 echo "                Setting Up Telemetry                 "
 echo "└─────────────────────────────────────────────────── "
-git clone --depth=1 https://github.com/kammce/Telemetry.git $TOOLDIR/Telemetry
-cd $TOOLDIR/Telemetry/ && ./setup
-cd $BASE
+rm -rf cd $TOOLDIR/Telemetry/
+git clone --depth=1 https://github.com/kammce/Telemetry.git "$TOOLDIR/Telemetry"
+cd "$TOOLDIR/Telemetry/" && ./setup
+cd "$BASE"
 echo " ───────────────────────────────────────────────────┐"
-echo "          Generating Environment Variables           "
+echo "        Generating Environment Variables File        "
 echo "└─────────────────────────────────────────────────── "
 cat > env.sh <<EOL
 #!/bin/bash
 # Setup a base directory:
-SJBASE=$BASE
+SJBASE="$BASE"
 
 # SJSUOne Board Settings:
-SJDEV=$SJSUONEDEV # Set this to your board ID
+SJDEV="$SJSUONEDEV" # Set this to your board ID
 SJBAUD=38400
 
 # Project Target Settings:
@@ -188,8 +215,8 @@ ENTITY=DBG
 
 # Compiler and library settings:
 # Selects compiler version to use
-PATH=\$PATH:\$SJBASE/tools/gcc-arm-none-eabi-6-2017-q2-update/bin
-SJLIBDIR="\$SJBASE/firmware/lib"
+PATH=\$(printf %q "\$PATH:\$SJBASE/tools/$ARM_GCC_COMMON/bin")
+SJLIBDIR="\$SJBASE/firmware/library"
 
 # Export everything to the environment
 export SJBASE
@@ -204,18 +231,31 @@ EOL
 echo " ───────────────────────────────────────────────────┐"
 echo "        Linking Files into Firmware projects         "
 echo "└─────────────────────────────────────────────────── "
-for PROJECT in HelloWorld FreeRTOS Telemetry Unittest
+# DEFAULT_PROJECTS=HelloWorld FreeRTOS Telemetry Unittest
+DEFAULT_PROJECTS=HelloWorld
+for PROJECT in $DEFAULT_PROJECTS
 do
 	# Place env.sh link into project folder
-	ln -s -f $BASE/env.sh firmware/$PROJECT/env.sh
+    rm -f "firmware/$PROJECT/env.sh"
+	ln -s -f "$BASE/env.sh" "firmware/$PROJECT/env.sh"
 	# Place makefile link into project folder
-	ln -s -f $BASE/makefile firmware/$PROJECT/makefile
-	# Place Unit test template folder into project folder
-	ln -s -f $BASE/tools/Unittest-Template/README.md firmware/$PROJECT/test/README.md
-	# Copy simple tests into project folder
-	cp -rf $BASE/tools/Unittest-Template/simple-test/ firmware/$PROJECT/test/
-	# Place the unit test makefile link into project folder
-	ln -s -f $BASE/makefile.test firmware/$PROJECT/test/simple-test/makefile
+    rm -f "firmware/$PROJECT/makefile"
+	ln -s -f "$BASE/makefile" "firmware/$PROJECT/makefile"
+
+    # ========================================================
+    # Unit Testing Setup Area
+    #    TODO: remove comment and fix when unit testing
+    #          has been installed.
+    # ========================================================
+
+    # # Place Unit test template folder into project folder
+    # rm -rf "firmware/$PROJECT/test/"
+    # mkdir -p "firmware/$PROJECT/test/"
+    # ln -s -f "$BASE/tools/Unittest-Template/README.md" "firmware/$PROJECT/test/README.md"
+	# # Copy simple tests into project folder
+	# cp -rf "$BASE/tools/Unittest-Template/simple-test/" "firmware/$PROJECT/test/"
+	# # Place the unit test makefile link into project folder
+	# ln -s -f "$BASE/makefile.test" "firmware/$PROJECT/test/simple-test/makefile"
 done
 echo " ───────────────────────────────────────────────────┐"
 echo "                   SETUP COMPLETE!                   "
