Setup detects toolkit download and extraction
Also fixes the makefile output sync issue.

Resolves #703
Resolves #701

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -22,7 +22,7 @@ TOOLS_BUNDLE_URL_LINUX="$TOOLS_BUNDLE_BASE_URL-linux.tar.bz2"
 TOOLS_BUNDLE_URL_OSX="$TOOLS_BUNDLE_BASE_URL-osx.tar.bz2"
 # Set later
 TOOLS_BUNDLE_URL=
-TOOLS_FILE_COUNT=9615
+TOOLS_FILE_COUNT=9621
 
 PREREQUISITES=1
 TOOL_BUNDLE=1
@@ -130,36 +130,78 @@ function install_python_tools()
   return $(($pip_status + $gcovr_status + $virtualenv_status))
 }
 
-function download_and_install_tool_bundle()
+function get_file_count()
 {
+  if [ ! -d "$1" ]; then
+    echo 0
+  else
+    echo $(tree -a "$1" | wc -l)
+  fi
+}
+
+function download_and_extract_tool_bundle()
+{
+  local tools_bundle_file_count=9621
   cd "$TOOLDIR/"
   echo " ───────────────────────────────────────────────────┐"
   echo "             Downloading Tools Bundle                "
   echo "└─────────────────────────────────────────────────── "
-  curl -C - -LO "$TOOLS_BUNDLE_URL"
+  local skipped_download=0
+  local temporary_name=temp_toolkit.tar.bz2
+  # Check that the file exists, if not, download it
+  if [ ! -f $(basename $TOOLS_BUNDLE_URL) ]; then
+    # Store file in temporary name first, so if this fails, this step does not
+    # get skipped.
+    echo "$TOOLS_BUNDLE_URL"
+    curl -L0 -o $temporary_name "$TOOLS_BUNDLE_URL"
+    mv $temporary_name "$(basename $TOOLS_BUNDLE_URL)"
+  else
+    echo "Tools bundle \"$(basename $TOOLS_BUNDLE_URL)\" already downloaded!"
+    echo "Skipping download..."
+    skipped_download=1
+  fi
+
   echo " ──────────────────────────────────────────────────┐"
   echo "             Extracting tools bundle                "
   echo "└────────────────────────────────────────────────── "
-  # Delete old openocd folder
-  rm -r "openocd" &>/dev/null
-  rm -r "gcc-arm*" &>/dev/null
-  rm -r "clang+llvm*" &>/dev/null
-  tar --verbose --extract --bzip --file="$(basename $TOOLS_BUNDLE_URL)" 2>&1 |
-  while read line; do
-      x=$((x+1))
-      echo -en "Extracting Progress: $(($x*100/$TOOLS_FILE_COUNT))%\r"
-  done
-	echo "Extracting Progress: 100%"
-  local extract=$?
-  # Verify that each directory exists
-  ls clang+llvm-*/ &> /dev/null
-  local clang_exists=$?
-  ls gcc-arm-none-eabi-*/ &> /dev/null
-  local gcc_exists=$?
-  ls openocd/ &> /dev/null
-  local openocd_exists=$?
+  # Check to see if tools have already been extracted
+  local openocd_file_count=$(get_file_count "openocd")
+  local gcc_arm_file_count=$(get_file_count gcc-arm*)
+  local clang_llvm_file_count=$(get_file_count clang+llvm*)
+  local total=$((openocd_file_count+gcc_arm_file_count+clang_llvm_file_count))
 
-  return $(($extract + $clang_exists + $gcc_exists + $openocd_exists))
+  if [ "$total" -eq "$TOOLS_FILE_COUNT" ] && \
+     [ "$skipped_download" -eq "1" ]
+  then
+    echo "Tools bundle \"$(basename $TOOLS_BUNDLE_URL)\" already extracted!"
+    echo "Skipping extraction..."
+    return 0
+  else
+    # Delete old toolkit folders
+    rm -r "openocd" &> /dev/null
+    rm -r "gcc-arm*" &> /dev/null
+    rm -r "clang+llvm*" &> /dev/null
+
+    tar --verbose --extract --bzip --file="$(basename $TOOLS_BUNDLE_URL)" \
+      2> /dev/null |
+    while read line; do
+        x=$((x+1))
+        echo -en "\rExtracting Progress: $(($x*100/$TOOLS_FILE_COUNT))% "
+    done
+    local extract=$?
+    echo -en "\rExtracting Progress: 100% \n"
+
+    # Verify that each directory exists
+    ls clang+llvm-*/ &> /dev/null
+    local clang_exists=$?
+    ls gcc-arm*/ &> /dev/null
+    local gcc_exists=$?
+    ls openocd/ &> /dev/null
+    local openocd_exists=$?
+
+    return $(($extract + $clang_exists + $gcc_exists + $openocd_exists))
+  fi
+  return 1
 }
 
 function install_nxpprog()
@@ -194,7 +236,7 @@ function generate_location_file()
 SJSU_DEV2_BASE         = $BASE
 PREVIOUS_SETUP_VERSION = $SETUP_VERSION
 
-ifeq (,\$(wildcard \$(SJSU_DEV2_BASE)))
+ifeq (,\$(wildcard \$(SJSU_DEV2_BASE)/))
 \$(info +-------------- SJSU-Dev2 Folder Not Found Error ---------------+)
 \$(info |                                                               |)
 \$(info | To update the location of SJSU-Dev2's folder run ./setup      |)
@@ -236,7 +278,11 @@ function final_install_check
   local location_file="$(print_status $LOCATION_FILE)"
   local project_link="$(print_status $LINK_PROJECTS)"
 
-  if [[ $1 -ne 0 ]]
+  local install_was_successful=$(($PREREQUISITES + $TOOL_BUNDLE + \
+                                  $PYTHON_TOOLS + $NXPPROG + $LOCATION_FILE + \
+                                  $LINK_PROJECTS))
+
+  if [[ $install_was_successful -ne "0" ]]
     then
     printf "\e[0;31m =========================== \e[0m\n"
     printf "\e[1;31m|   Something went wrong!   |\e[0m\n"
@@ -318,7 +364,7 @@ else
   exit 1
 fi
 
-download_and_install_tool_bundle  ; TOOL_BUNDLE=$?
+download_and_extract_tool_bundle  ; TOOL_BUNDLE=$?
 install_python_tools              ; PYTHON_TOOLS=$?
 install_nxpprog                   ; NXPPROG=$?
 generate_location_file            ; LOCATION_FILE=$?
@@ -326,6 +372,4 @@ link_projects                     ; LINK_PROJECTS=$?
 
 echo ""
 
-final_install_check \
-  $(($PREREQUISITES + $TOOL_BUNDLE + $PYTHON_TOOLS + \
-     $NXPPROG + $LOCATION_FILE + $LINK_PROJECTS))
+final_install_check
